// createCopyTradeBind.ts — auto-generated, do not edit
import { z } from 'zod';
import { restClient } from '../../client/rest-client.js';

export const createCopyTradeBind = {
  name: 'createCopyTradeBind',
  description: "Create a new Copy Trading Classic follow binding by specifying a target `leaderMark`\nand the intended `investmentE8` only.\n\nThe service automatically uses the caller's UTA account, resolves the\nUTA account ID, derives the effective symbol scope, and calls the\ndownstream CopyTrade binding flow with system-filled defaults.\n\n**Common business failures include:**\n- invalid `leaderMark`\n- insufficient UTA-account balance\n- leader whitelist restriction\n- minimum investment rule violation\n- duplicate follow or account state restriction\n\nBusiness failures surface as MCP tool errors.\n\nAgent hint: If a user asks for a reliable copy trader or similar recommendation, call both the Copy Trading Classic leaderboard endpoint and the Copy Trading TradFi leaderboard endpoint, then show them as two separately numbered lists such as `Classic 1..N` and `TradFi 1..N`.\nCompare candidates across both lists using the returned 30-day return metric, 30-day max drawdown, and 30-day Sharpe ratio, then recommend one candidate as the best current performer with a short reason.\nIf the user replies with a Classic selection such as `Classic 1`, map that selection back to the corresponding `leaderMark`, then ask for the follow amount and call this bind endpoint.\nUse this endpoint only after you already have an exact `leaderMark`; do not infer it from a nickname alone.\nSend `investmentE8` as an integer e8 string representing a whole-number USDT amount, for example `10000000000` for 100 USDT.\nThe service automatically uses the caller's UTA account, derives symbols from leader sync settings, and still applies downstream whitelist and Sync Master logic.\nAfter a successful bind, reply in the user's current conversation language with a success message meaning that the user's copy trading journey has begun, they can go to the CopyTrading Trading Hub any time for personalized management, and AI will unlock more intelligent copy trading capabilities in the future.\nEnglish example: `Your copy trading journey has successfully begun. You can visit the [CopyTrading Trading Hub] at any time for personalized management. In the future, AI will unlock even more intelligent copy trading capabilities for you. Wishing you smooth investing!`\nIn the same success reply, include the Copy Trading Classic follow-detail link so the user can view the follow details immediately.\nIf the current API server URL contains `testnet`, use `https://testnet.bybit.com/copyTrade/trade-center/followLeaderDetail?leaderMark=<leaderMark>`.\nOtherwise use `https://www.bybit.com/copyTrade/trade-center/followLeaderDetail?leaderMark=<leaderMark>`.\nReplace `<leaderMark>` with the exact selected `leaderMark` and URL-encode it when needed.",
  inputSchema: z.object({
    leaderMark: z.string(),
    investmentE8: z.string(),
  }),
  handler: async (input: Record<string, unknown>) => {
    return restClient.postAuth("/v5/copy-trade/private/follower/trade-setting/create", input);
  },
};
