// getPreUpgradeTransactionLog.ts — auto-generated, do not edit
import { z } from 'zod';
import { restClient } from '../../client/rest-client.js';

export const getPreUpgradeTransactionLog = {
  name: 'getPreUpgradeTransactionLog',
  description: "Query pre-upgrade transaction logs. After the account is upgraded to a Unified account, use this endpoint to get the transaction logs which occurred before the upgrade.\n- Only supports querying USDC Perpetual and Options transaction logs\n- Supports `linear` (USDC Perps) and `option` categories\n\n**Time range rules:**\n- Without both `startTime` and `endTime`: returns last 7 days by default\n- Only `startTime` provided: returns from startTime to startTime + 7 days\n- Only `endTime` provided: returns from endTime - 7 days to endTime\n- Both provided: endTime - startTime must be <= 7 days\n\n**Gaia route:** `V5_OPENAPI_QUERY_PRE_UPGRADE_TRANSLOG`",
  inputSchema: z.object({
    category: z.enum(["linear", "option"]),
    baseCoin: z.string().optional(),
    type: z.enum(["TRADE", "SETTLEMENT", "DELIVERY", "LIQUIDATION", "PART_LIQUIDATION", "ADL", "CLOSEPNL", "POSITION_TAKE_OVER", "TRANSFER_IN", "TRANSFER_OUT", "INSURANCE_FUND", "FEE_REFUND", "INTEREST", "FIXED_INTEREST", "FIXED_INTEREST_REFUND", "BONUS", "BONUS_RECOLLECT", "BONUS_TRANSFER_IN", "BONUS_TRANSFER_OUT", "AIRDROP", "AIRDROP_OUT", "AIRDROP_EFTD", "AIRDROP_OUT_EFTD", "AIRDROP_FIAT", "AIRDROP_OUT_FIAT", "OTC_TRADE", "CURRENCY_BUY", "CURRENCY_SELL", "CURRENCY_BUY_MANUEL", "CURRENCY_SELL_MANUEL", "AUTO_DEDUCTION", "PERP_SYMBOL_SETTLE", "SPREAD_FEE_OUT", "MANUAL_LOANS_BORROW", "MANUAL_LOANS_REPAY", "AUTO_LOANS_BORROW", "AUTO_LOANS_REPAY", "SPOT_REPAYMENT_BUY", "SPOT_REPAYMENT_SELL", "LOANS_ASSET_REDEMPTION", "LOANS_PLEDGE_ASSET", "LOANS_BORROW_FUNDS", "LOANS_REPAY_FUNDS", "INSTITUTION_LOAN_IN", "INSTITUTION_PAYBACK_PRINCIPAL_OUT", "INSTITUTION_PAYBACK_INTEREST_OUT", "INSTITUTION_EXCHANGE_SELL", "INSTITUTION_EXCHANGE_BUY", "INSTITUTION_LIQ_PRINCIPAL_OUT", "INSTITUTION_LIQ_INTEREST_OUT", "INSTITUTION_LOAN_TRANSFER_IN", "INSTITUTION_LOAN_TRANSFER_OUT", "INSTITUTION_LOAN_WITHOUT_WITHDRAW", "INSTITUTION_LOAN_RESERVE_IN", "INSTITUTION_LOAN_RESERVE_OUT", "PREMARKET_TRANSFER_IN", "PREMARKET_TRANSFER_OUT", "PREMARKET_DELIVERY_SELL_NEW_COIN", "PREMARKET_DELIVERY_BUY_NEW_COIN", "PREMARKET_DELIVERY_PLEDGE_PAY_SELLER", "PREMARKET_DELIVERY_PLEDGE_BACK", "PREMARKET_ROLLBACK_PLEDGE_BACK", "PREMARKET_ROLLBACK_PLEDGE_PENALTY_TO_BUYER", "TOKENS_SUBSCRIPTION", "TOKENS_REDEMPTION", "FLEXIBLE_STAKING_SUBSCRIPTION", "FLEXIBLE_STAKING_REDEMPTION", "FLEXIBLE_STAKING_REFUND", "FIXED_STAKING_SUBSCRIPTION", "FIXED_STAKING_REFUND", "ONCHAINEARN_SUBSCRIPTION", "ONCHAINEARN_REFUND", "ONCHAINEARN_REDEMPTION", "ONCHAINEARN_REDEMPTION_PRINCIPAL", "ONCHAINEARN_LST", "DEFI_INVESTMENT_SUBSCRIPTION", "DEFI_INVESTMENT_REFUND", "DEFI_INVESTMENT_REDEMPTION", "STRUCTURE_PRODUCT_SUBSCRIPTION", "STRUCTURE_PRODUCT_REFUND", "CLASSIC_WEALTH_MANAGEMENT_SUBSCRIPTION", "PREMIUM_WEALTH_MANAGEMENT_SUBSCRIPTION", "PREMIUM_WEALTH_MANAGEMENT_REFUND", "LIQUIDITY_MINING_SUBSCRIPTION", "LIQUIDITY_MINING_REFUND", "PWM_SUBSCRIPTION", "PWM_REFUND", "CUSTODY_LOCK", "CUSTODY_UNLOCK", "CUSTODY_UNLOCK_REFUND", "CUSTODY_NETWORK_FEE", "CUSTODY_SETTLE_FEE", "PLATFORM_TOKEN_MNT_LIQRECALLEDMMNT", "PLATFORM_TOKEN_MNT_LIQRETURNEDMNT", "PEF_TRANSFER_IN", "PEF_TRANSFER_OUT", "PEF_PROFIT_SHARE"]).optional(),
    startTime: z.number().int().optional(),
    endTime: z.number().int().optional(),
    limit: z.number().int().min(1).max(50).default(20).optional(),
    cursor: z.string().optional(),
  }),
  handler: async (input: Record<string, unknown>) => {
    return restClient.getAuth("/v5/pre-upgrade/account/transaction-log", input);
  },
};
